const data = [
  {
    name: "Sambousik",
    category: "Starters",
    unit: "Dozen",
    price: 7,
    page: 1,
  },
  {
    name: "Kabkoub Lahme",
    category: "Starters",
    unit: "Dozen",
    price: 8,
    page: 1,
  },
  {
    name: "Kabkoub Labniyeh",
    category: "Starters",
    unit: "Dozen",
    price: 6,
    page: 1,
  },
  {
    name: "Kabkoub bel jeben",
    category: "Starters",
    unit: "Dozen",
    price: 8,
    page: 1,
  },
  {
    name: "Re2a2at Jebne",
    category: "Starters",
    unit: "Dozen",
    price: 7,
    page: 1,
  },
  {
    name: "Re2a2at Sojo2",
    category: "Starters",
    unit: "Dozen",
    price: 7,
    page: 1,
  },
  {
    name: "Re2a2at Fajita",
    category: "Starters",
    unit: "Dozen",
    price: 8,
    page: 1,
  },
  {
    name: "Pizza",
    category: "Starters",
    unit: "Dozen",
    price: 8,
    page: 1,
  },
  {
    name: "Hot Dog",
    category: "Starters",
    unit: "Dozen",
    price: 8,
    page: 1,
  },
  {
    name: "Lahem Bi 3ajin",
    category: "Starters",
    unit: "Dozen",
    price: 7,
    page: 1,
  },
  {
    name: "Lahem Bi 3ajin Soiree",
    category: "Starters",
    unit: "Dozen",
    price: 8,
    page: 1,
  },
  {
    name: "Spring Rolls",
    category: "Starters",
    unit: "Dozen",
    price: 6,
    page: 1,
  },
  {
    name: "Ftayer Keshek",
    category: "Starters",
    unit: "Dozen",
    price: 6,
    page: 1,
  },
  {
    name: "Ftayer Sbenegh",
    category: "Starters",
    unit: "Dozen",
    price: 6,
    page: 1,
  },
  {
    name: "Crabe Salade",
    category: "Salade",
    unit: "4 Pers",
    price: 20,
    page: 2,
  },
  {
    name: "Greek Salade",
    category: "Salade",
    unit: "4 Pers",
    price: 20,
    page: 2,
  },
  {
    name: "Pasta Salade",
    category: "Salade",
    unit: "4 Pers",
    price: 20,
    page: 2,
  },
  {
    name: "Ckicken Ceaser Salade",
    category: "Salade",
    unit: "4 Pers",
    price: 20,
    page: 2,
  },
  {
    name: "Tabbouleh",
    category: "Salade",
    unit: "4 Pers",
    price: 15,
    page: 2,
  },
  {
    name: "Fattoush",
    category: "Salade",
    unit: "4 Pers",
    price: 15,
    page: 2,
  },
  {
    name: "Kebbe Mamdoude",
    category: "Kebbe",
    unit: "kg",
    price: 13,
    page: 2,
  },
  {
    name: "Kebbe Ma3 Basal w Loz",
    category: "Kebbe",
    unit: "kg",
    price: 15,
    page: 2,
  },
  {
    name: "Eres kebbe Shahem",
    category: "Kebbe",
    unit: "pc",
    price: 4.5,
    page: 2,
  },
  {
    name: "Eres kebbe Lahem",
    category: "Kebbe",
    unit: "pc",
    price: 5,
    page: 2,
  },
  {
    name: "Salsa Harra",
    category: "Kebbe",
    unit: "kg",
    price: 5,
    page: 2,
  },
  {
    name: "Wara2 3enab Zet",
    category: "Main Dishes",
    unit: "kg",
    price: 8,
    page: 3,
  },
  {
    name: "Wara2 3enab Lahme",
    category: "Main Dishes",
    unit: "kg",
    price: 14,
    page: 3,
  },
  {
    name: "Chicken Fingers",
    category: "Main Dishes",
    unit: "kg",
    price: 14,
    page: 3,
  },
  {
    name: "Bajaxy",
    category: "Main Dishes",
    unit: "kg",
    price: 20,
    page: 3,
  },
  {
    name: "Crispy",
    category: "Main Dishes",
    unit: "kg",
    price: 14,
    page: 3,
  },
  {
    name: "Escalope",
    category: "Main Dishes",
    unit: "kg",
    price: 14,
    page: 3,
  },
  {
    name: "Fajita",
    category: "Main Dishes",
    unit: "kg",
    price: 14,
    page: 3,
  },
  {
    name: "Mahshe Sele2",
    category: "Main Dishes",
    unit: "kg",
    price: 8,
    page: 3,
  },
  {
    name: "Mahshe Malfouf",
    category: "Main Dishes",
    unit: "kg",
    price: 12,
    page: 3,
  },
  // {
  //   name: "Shishbarak  /100 pcs",
  //   category: "Main Dishes",
  //   unit: "100 pc",
  //   price: 7,
  //   page: 3,
  // },
  {
    name: "Shishbarak Kbir  /100 pcs",
    category: "Main Dishes",
    unit: "100 pc",
    price: 8,
    page: 3,
  },
  {
    name: "Gateau ",
    category: "Dessert",
    unit: "pc",
    price: 10,
    page: 4,
  },
  {
    name: "Gateau Chocolat",
    category: "Dessert",
    unit: "pc",
    price: 12,
    page: 4,
  },
  {
    name: "Gateau Ananas",
    category: "Dessert",
    unit: "pc",
    price: 12,
    page: 4,
  },
  {
    name: "Petit Four /kg",
    category: "Dessert",
    unit: "kg",
    price: 10,
    page: 4,
  },
  {
    name: "Zet Zaytoun",
    category: "Specials",
    unit: "1 L",
    price: 5,
    page: 4,
  },
  {
    name: "Apple Vinegar",
    category: "Specials",
    unit: "1 L",
    price: 3,
    page: 4,
  },
  {
    name: "Sauce",
    category: "Specials",
    unit: "1 L",
    price: 4,
    page: 4,
  },
  {
    name: "Delivery",
    category: "Delivery",
    price: 3,
    page: 4,
  },
];
